### ISSUE TITLE
E2E tests failing in CI

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#109]
@Enkidu93  - can you investigate and see why they would be failing?  They pass when run locally...

https://github.com/sillsdev/serval/actions/runs/6050301911/job/16419334108

```csharp
Passed CircuitousRouteGetWordGraphAsync [32 s]
  Passed CircuitousRouteTranslateTopNAsync [16 s]
  Passed GetEchoPretranslate [972 ms]
  Failed GetEchoSuggestion [50 ms]
  Error Message:
   System.ArgumentException : An item with the same key has already been added. Key: Echo1
  Stack Trace:
     at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at ServalClientHelper.CreateNewEngine(String engineTypeString, String source_language, String target_language, String name) in /home/runner/work/serval/serval/src/Serval.Client/ServalClientHelper.cs:line [81](https://github.com/sillsdev/serval/actions/runs/6050301911/job/16419334108#step:11:82)
   at Serval.ApiServerE2E.E2ETests.GetEchoSuggestion() in /home/runner/work/serval/serval/tests/Serval.E2ETests/E2ETests.cs:line 61
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()

  Passed GetNmtCancelAndRestartBuild [12 s]
  Passed GetSmtAddSegment [25 s]
  Failed GetSmtCancelAndRestartBuild [4 s]
  Error Message:
   Serval.Client.ServalApiException : There is already an active/pending build

Status: 409
Response: 
{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.8","title":"Conflict","status":409,"traceId":"00-ab98348a4f4295942e71dcc6c42117ea-75627b82d303dc32-00"}
  Stack Trace:
     at Serval.Client.TranslationEnginesClient.StartBuildAsync(String id, TranslationBuildConfig buildConfig, CancellationToken cancellationToken) in /home/runner/work/serval/serval/src/Serval.Client/Client.g.cs:line 3025
   at ServalClientHelper.StartBuildAsync(String engineId) in /home/runner/work/serval/serval/src/Serval.Client/ServalClientHelper.cs:line 87
   at ServalClientHelper.BuildEngine(String engineId) in /home/runner/work/serval/serval/src/Serval.Client/ServalClientHelper.cs:line 92
   at Serval.ApiServerE2E.E2ETests.GetSmtCancelAndRestartBuild() in /home/runner/work/serval/serval/tests/Serval.E2ETests/E2ETests.cs:line 321
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()

  Passed GetSmtMoreCorpus [27 s]
  Passed GetSmtTranslation [24 s]
NUnit Adapter 4.4.0.0: Test execution complete
  Passed NmtBatch [4 m 53 s]

Test Run Failed.
Total tests: 10
     Passed: 8
     Failed: 2
```

**Comment by johnml1135** [comment]
Also, can you add a workflow dispatch onto the E2E CI?  It might be nice to run it on a separate branch before pulling it into main.
