### ISSUE TITLE
Update file leads to duplicate key?

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#112]
```
**Resolved**Value: [ var='B0' metric='{app="serval-api", container="serval-api", container_id="0b023fae01329663303b62d8105fe4e940de53655166e820393606618ec44028", host="kb3", log="\x1b[41m\x1b[30mfail\x1b[39m\x1b[22m\x1b[49m: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id \"0HMT43IG3F5EL\", Request id \"0HMT43IG3F5EL:0000000C\": An unhandled exception was thrown by the application.
      SIL.DataAccess.DuplicateKeyException: The inserted/updated entity has the same key as an existing entity.
         at SIL.DataAccess.MongoRepository`1.TryCatchDuplicate[TR](Func`1 func) in /app/src/SIL.DataAccess/MongoRepository.cs:line 242
         at SIL.DataAccess.MongoRepository`1.InsertAsync(T entity, CancellationToken cancellationToken) in /app/src/SIL.DataAccess/MongoRepository.cs:line 72
         at Serval.DataFiles.Services.DataFileService.UpdateAsync(String id, Stream stream, CancellationToken cancellationToken) in /app/src/Serval.DataFiles/Services/DataFileService.cs:line 102
         at Serval.DataFiles.Controllers.DataFilesController.UpdateAsync(String id, IFormFile file, CancellationToken cancellationToken) in /app/src/Serval.DataFiles/Controllers/DataFilesController.cs:line 175
         at lambda_method21237(Closure , Object )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at
```

Why did this happen?  What is going on?

**Comment by johnml1135** [comment]
This is putting an entry into the deleted files:
```csharp
                await _deletedFiles.InsertAsync(
                    new DeletedFile
                    {
                        Id = originalDataFile.Id,
                        Filename = originalDataFile.Filename,
                        DeletedAt = DateTime.UtcNow
                    },
                    cancellationToken
                );
```

We can add a try catch around this.

**Comment by johnml1135** [comment]
This is related to #104.

**Comment by Enkidu93** [comment]
Is this issue also covered in your solution to #104? Or does it still need to be addressed?

**Comment by ddaspit** [comment]
Originally, an ID was generated for each new `DeletedFile` doc that was inserted. At some point, this was changed to use the same ID as the `DataFile` doc. I'm not sure why this was done. This change introduced this issue and #104. We cannot use the same ID as the `DataFile`, since multiple `DeletedFile` docs can be generated for the same `DataFile`. This results in the `DuplicateKeyException`. If we revert back to the original behavior, it should fix both issues.

**Comment by Enkidu93** [comment]
> Originally, an ID was generated for each new `DeletedFile` doc that was inserted. At some point, this was changed to use the same ID as the `DataFile` doc. I'm not sure why this was done. This change introduced this issue and #104. We cannot use the same ID as the `DataFile`, since multiple `DeletedFile` docs can be generated for the same `DataFile`. This results in the `DuplicateKeyException`. If we revert back to the original behavior, it should fix both issues.

I see. Excellent!
