### ISSUE TITLE
Build stays in active state after completing

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#115]
On qa.serval-api.org:
```
[
  {
    "id": "64f6360e6f044714a98d9ced",
    "url": "/api/v1/translation/engines/64f6360c6f044714a98d9cd9/builds/64f6360e6f044714a98d9ced",
    "revision": 3,
    "engine": {
      "id": "64f6360c6f044714a98d9cd9",
      "url": "/api/v1/translation/engines/64f6360c6f044714a98d9cd9"
    },
    "pretranslate": [
      {
        "corpus": {
          "id": "64f6360e6f044714a98d9cec",
          "url": "/api/v1/translation/engines/64f6360c6f044714a98d9cd9/corpora/64f6360e6f044714a98d9cec"
        }
      }
    ],
    "step": 10,
    "state": "Active"
  }
]
```
![image](https://github.com/sillsdev/serval/assets/13733556/43e148ff-23de-4338-a95d-f115b5d95454)

What is going on?

**Comment by johnml1135** [comment]
And it failed...
![image](https://github.com/sillsdev/serval/assets/13733556/d6acc980-331f-4a07-8017-04f47363bc9f)

**Comment by johnml1135** [comment]
Actually, here is the hangfire error:
```
Amazon.S3.AmazonS3Exception: Access Denied
 ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RedirectHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at SIL.Machine.AspNetCore.Services.S3FileStorage.Rm(String path, Boolean recurse, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs:line 94
   at SIL.Machine.AspNetCore.Services.SharedFileService.DeleteAsync(String path, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/SharedFileService.cs:line 71
   at SIL.Machine.AspNetCore.Services.ClearMLNmtEngineBuildJob.RunAsync(String engineId, String buildId, IReadOnlyList`1 corpora, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs:line 217
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by johnml1135** [comment]
![image](https://github.com/sillsdev/serval/assets/13733556/45a74807-6ab5-4ae6-bbb3-2a6a739c2309)

**Comment by ddaspit** [comment]
It looks like it crashed [in the exception handler](https://github.com/sillsdev/machine/blob/5e5312f5f15b9991a7703530296fd3d337eb6c3b/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs#L217) of the job prior to updating the state and notifying Serval.

**Comment by ddaspit** [comment]
This is another reason why it would be useful to get rid of the NMT Hangfire job.
