### ISSUE TITLE
E2E - more tests failing

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#119]
https://github.com/sillsdev/serval/actions/runs/6089224109/job/16521561854

Eli - can you see if you can resolve these last E2E issues?

```
  Failed CircuitousRouteGetWordGraphAsync [2 s]
  Error Message:
   Serval.Client.ServalApiException : The engine was specified incorrectly.  Did you use the same language for the source and target?

Status: 422
Response: 
"Status(StatusCode=\"InvalidArgument\", Detail=\"The engine type is invalid.\")"
  Stack Trace:
     at Serval.Client.TranslationEnginesClient.CreateAsync(TranslationEngineConfig engineConfig, CancellationToken cancellationToken) in /home/runner/work/serval/serval/src/Serval.Client/Client.g.cs:line 1296
   at ServalClientHelper.CreateNewEngine(String engineTypeString, String source_language, String target_language, String name) in /home/runner/work/serval/serval/tests/Serval.E2ETests/ServalClientHelper.cs:line 72
   at Serval.E2ETests.ServalApiTests.CircuitousRouteGetWordGraphAsync() in /home/runner/work/serval/serval/tests/Serval.E2ETests/ServalApiTests.cs:line 213
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.DelegatingTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```

and

```
Failed CircuitousRouteTranslateTopNAsync [437 ms]
Failed GetSmtAddSegment [554 ms]
Failed GetSmtMoreCorpus [477 ms]
Failed GetSmtTranslation [409 ms]
```

It looks like all the SMT tests fail...

**Comment by Enkidu93** [comment]
These are all passing locally - still investigating

**Comment by Enkidu93** [comment]
I don't think so. I can re-verify though. 422 is only thrown because of invalid engine type or invalid src/trg languages. I know that the run was cancelled because it was exceeding the 15 minute limit I put (we can change that if you like), but I don't think - even if it canceled mid-test - that it would cause such a result.

**Comment by Enkidu93** [comment]
Caused by a solution to https://github.com/sillsdev/machine/issues/67

**Comment by johnml1135** [comment]
Even more tests failing - let's see if we can fix these as well today: https://github.com/sillsdev/serval/actions/runs/6099025334/job/16550211190

**Comment by Enkidu93** [comment]
So there seem to be a host of distinct but related issues causing this particular test to fail. It can fail because:
* The build completes before the cancellation process begins, yielding a 404.
* The build attempts to start a new build before the cancellation goes through, yielding a 409.
* And occasionally, Mongo will fail mid-findOneAndUpdate - I imagine this is an issue with concurrent modification of the document.

In order to make the test less prone to false negatives due to these race conditions, I've removed the delay between the initial build and the cancellation and I've increased the delay between the cancellation and the second build attempt. I'm not sure of a good way to address these other issues. I don't know that it's unreasonable for a user to expect a delay in these processes (they certainly do with building after all). A service that more directly interacts with users could always poll (or use webhooks) to see if it has completed etc.

**Comment by Enkidu93** [comment]
Opening a separate issue to be addressed as needed: https://github.com/sillsdev/serval/issues/122

**Comment by ddaspit** [comment]
@Enkidu93 Can you give more information on the failure while calling findOneAndUpdate in Mongo? Is the Mongo driver throwing an exception?
