### ISSUE TITLE
Language tag breaking change

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#197]
```
  |   | 2023-10-25 15:58:37 | machine-job: 2023-10-25T19:58:37.385407906Z fail: SIL.Machine.AspNetCore.Services.NmtPreprocessBuildJob[0]       Build faulted (65397369222f10274a9616c9)       System.NullReferenceException: Object reference not set to an instance of an object.
          at SIL.Machine.AspNetCore.Services.NmtClearMLBuildJobFactory.ConvertLanguageTag(String languageTag) in /app/src/SIL.Machine.AspNetCore/Services/NmtClearMLBuildJobFactory.cs:line 58
          at SIL.Machine.AspNetCore.Services.NmtClearMLBuildJobFactory.CreateJobScriptAsync(String engineId, String buildId, String stage, Object data, String buildOptions, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/NmtClearMLBuildJobFactory.cs:line 54
          at SIL.Machine.AspNetCore.Services.ClearMLBuildJobRunner.CreateJobAsync(TranslationEngineType engineType, String engineId, String buildId, String stage, Object data, String buildOptions, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/ClearMLBuildJobRu
```

**Comment by Enkidu93** [comment]
This a log from a build run post-the-language-tag-changes-Damien-made? It seems like the same error message we were getting before.

**Comment by johnml1135** [comment]
This is before the change.  There is nothing to do - it is already fixed.
