### ISSUE TITLE
Mongo shoudn't need to come up first

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#244]
We have had a few times where Mongo goes down and then comes up.  Serval gets broken and does not self-heal.

**Comment by johnml1135** [comment]
This issue can be recreated by spinning up docker compose, then removing the mongo container than re-spinning up docker compose.  The errror is:
```
machine-engine-cntr  | fail: Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService[103]
machine-engine-cntr  |       Health check Mongo with status Unhealthy completed after 30001.435ms with message '(null)'
machine-engine-cntr  |       System.OperationCanceledException: The operation was canceled.
machine-engine-cntr  |          at System.Threading.CancellationToken.ThrowOperationCanceledException()
machine-engine-cntr  |          at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChangedHelper.HandleCompletedTask(Task completedTask)
machine-engine-cntr  |          at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChangedAsync(IServerSelector selector, ClusterDescription description, Task descriptionChangedTask, TimeSpan timeout, CancellationToken cancellationToken)
machine-engine-cntr  |          at MongoDB.Driver.Core.Clusters.Cluster.SelectServerAsync(IServerSelector selector, CancellationToken cancellationToken)
machine-engine-cntr  |          at MongoDB.Driver.Core.Clusters.IClusterExtensions.SelectServerAndPinIfNeededAsync(ICluster cluster, ICoreSessionHandle session, IServerSelector selector, CancellationToken cancellationToken)
```

**Comment by johnml1135** [comment]
I'm also getting:
```
fail: Hangfire.Mongo.DistributedLock.MongoDistributedLock[0]
serval_cntr          |       Hangfire:recurring-jobs:lock - Unable to clean up locks on the resource. Details:
serval_cntr          |       System.TimeoutException: A timeout occurred after 30000ms selecting a server using CompositeServerSelector{ Selectors = WritableServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 }, OperationsCountServerSelector }. Client view of cluster state is { ClusterId : "2", ConnectionMode : "ReplicaSet", Type : "ReplicaSet", State : "Disconnected", Servers : [{ ServerId: "{ ClusterId : 2, EndPoint : "Unspecified/mongo:27017" }", EndPoint: "Unspecified/mongo:27017", ReasonChanged: "ReportedPrimaryIsStale", State: "Disconnected", ServerVersion: , TopologyVersion: , Type: "Unknown", LastHeartbeatTimestamp: null, LastUpdateTimestamp: "2023-12-20T13:18:29.1952761Z" }] }.
serval_cntr          |          at MongoDB.Driver.Core.Clusters.Cluster.ThrowTimeoutException(IServerSelector selector, ClusterDescription description)
serval_cntr          |          at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChangedHelper.HandleCompletedTask(Task completedTask)
serval_cntr          |          at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChanged(IServerSelector selector, ClusterDescription description, Task descriptionChangedTask, TimeSpan timeout, CancellationToken cancellationToken)
serval_cntr          |          at MongoDB.Driver.Core.Clusters.Cluster.SelectServer(IServerSelector selector, CancellationToken cancellationToken)
serval_cntr          |          at MongoDB.Driver.Core.Bindings.WritableServerBinding.GetWriteChannelSource(CancellationToken cancellationToken)
serval_cntr          |          at MongoDB.Driver.Core.Bindings.ReadWriteBindingHandle.GetWriteChannelSource(CancellationToken cancellationToken)
serval_cntr          |          at MongoDB.Driver.Core.Operations.RetryableWriteContext.Initialize(CancellationToken cancellationToken)
```
which may be related to https://github.com/Hangfire-Mongo/Hangfire.Mongo/issues/378

**Comment by johnml1135** [comment]
So, after investigating more, if I map a volume for mongoDB in docker-compose, such as:
```
    volumes:
      - /var/lib/mongodb:/data/db
```
the error goes away and the database starts back up fine.  I believe it is that hangfire created the database and can't find it anymore, as it actually looks for the unique ID.  When the underlying database is persistent, everything is fine.  There may still be an issue, but this means of reacreating it is a red herring.

**Comment by johnml1135** [comment]
Here is the issue - if Mongo is not up by the time (or shortly after) macine-engine, etc. are up, machine-engine will fail in an unrecoverable state, but not actually crash.  Therefore, it will get stuck.  This should not be - it should self heal by either auto-quitting or (more ideally) connecting when the service becomes available.

**Comment by johnml1135** [comment]
I can't reproduce this easily.  There is better monitoring now.  I will just let it ride for now unless it comes back up.
