### ISSUE TITLE
Out of Memory for 24GB GPU - E2E test

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#323]
https://app.sil.hosted.allegro.ai/projects/*/experiments/1bdb2c3fa30b46dca08c2015b7d6fa12/info-output/log?columns=selected&columns=type&columns=name&columns=tags&columns=status&columns=project.name&columns=users&columns=started&columns=last_update&columns=last_iteration&columns=parent.name&order=-last_update&filter=status:failed&deep=true

```
ClearML Monitor: Could not detect iteration reporting, falling back to iterations as seconds-from-start
2024-02-14 16:12:52
  0% 0/10 [00:00<?, ?it/s][WARNING|logging.py:290] 2024-02-14 16:12:48,703 >> You're using a NllbTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
2024-02-14 16:12:53
User aborted: stopping task (3)
2024-02-14 16:12:53
Traceback (most recent call last):
  File "/root/.clearml/venvs-builds/3.11/code/untitled.py", line 14, in <module>
    run(args)
  File "/usr/local/lib/python3.11/dist-packages/machine/jobs/build_nmt_engine.py", line 79, in run
    raise e
  File "/usr/local/lib/python3.11/dist-packages/machine/jobs/build_nmt_engine.py", line 71, in run
    job.run(progress, check_canceled)
  File "/usr/local/lib/python3.11/dist-packages/machine/jobs/nmt_engine_build_job.py", line 71, in run
    model_trainer.train(progress=phase_progress, check_canceled=check_canceled)
  File "/usr/local/lib/python3.11/dist-packages/machine/translation/huggingface/hugging_face_nmt_model_trainer.py", line 361, in train
    train_result = self._trainer.train(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/transformers/trainer.py", line 1591, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/transformers/trainer.py", line 1971, in _inner_training_loop
    self.optimizer.step()
  File "/usr/local/lib/python3.11/dist-packages/accelerate/optimizer.py", line 132, in step
    self.scaler.step(self.optimizer, closure)
  File "/usr/local/lib/python3.11/dist-packages/torch/cuda/amp/grad_scaler.py", line 416, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/cuda/amp/grad_scaler.py", line 315, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/accelerate/optimizer.py", line 185, in patched_step
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/optim/lr_scheduler.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/optim/optimizer.py", line 373, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/optim/adamw.py", line 184, in step
    adamw(
  File "/usr/local/lib/python3.11/dist-packages/torch/optim/adamw.py", line 335, in adamw
    func(
  File "/usr/local/lib/python3.11/dist-packages/torch/optim/adamw.py", line 599, in _multi_tensor_adamw
    exp_avg_sq_sqrt = torch._foreach_sqrt(device_exp_avg_sqs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacty of 23.68 GiB of which 14.56 MiB is free. Process 3848501 has 23.66 GiB memory in use. Of the allocated memory 23.01 GiB is allocated by PyTorch, and 342.19 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by johnml1135** [comment]
We should also back off of batch size when training, just like we do with pretranslating.
