### ISSUE TITLE
Error when running build using scriptureRange: "TransientAccessException : translation not found in transient JSON stream or already passed in this stream"

### ISSUE THREAD

**Issue by pmachapman** [sillsdev/serval#364]
I am getting an unusual error when I am specifying the books using scripture ranges. Both the source and target have the books in the trainOn and pretranslate scriptureRange, (source is the NRSV, target is a translation in Māori).

Am I specifying the scripture range wrong?

```json
  {
    "id": "661d9760624b51027a9e83ab",
    "url": "/api/v1/translation/engines/66172578624b51027a9e7c3b/builds/661d9760624b51027a9e83ab",
    "revision": 9,
    "engine": {
      "id": "66172578624b51027a9e7c3b",
      "url": "/api/v1/translation/engines/66172578624b51027a9e7c3b"
    },
    "trainOn": [
      {
        "corpus": {
          "id": "6617257e624b51027a9e7c3e",
          "url": "/api/v1/translation/engines/66172578624b51027a9e7c3b/corpora/6617257e624b51027a9e7c3e"
        },
        "scriptureRange": "PHM;2JN;3JN"
      }
    ],
    "pretranslate": [
      {
        "corpus": {
          "id": "6617257e624b51027a9e7c3e",
          "url": "/api/v1/translation/engines/66172578624b51027a9e7c3b/corpora/6617257e624b51027a9e7c3e"
        },
        "scriptureRange": "SNG;LAM"
      }
    ],
    "step": 0,
    "percentCompleted": 0.9,
    "message": "TransientAccessException : translation not found in transient JSON stream or already passed in this stream",
    "queueDepth": 0,
    "state": "Faulted",
    "dateFinished": "2024-04-15T21:29:32.867Z",
    "options": {
      "max_steps": 20
    }
  }
```

**Comment by johnml1135** [comment]
Here is the [log from ClearML](https://app.sil.hosted.allegro.ai/projects/*/experiments/d19d60c7e5b64fdb8e95341955e8c622/info-output/log?columns=selected&columns=type&columns=name&columns=tags&columns=status&columns=project.name&columns=users&columns=started&columns=last_update&columns=last_iteration&columns=parent.name&order=-last_update&filter=&deep=true):
```
2024-04-15 17:29:21,638 - machine.jobs.nmt_engine_build_job - INFO - Pretranslating segments
2024-04-15 17:29:27
2024-04-15 17:29:23,280 - clearml.storage - INFO - Downloading: 5.00MB / 5.00MB @ 3.50MBs from s3://aqua-ml-data/ext-qa/builds/661d9760624b51027a9e83ab/pretranslate.src.json
2024-04-15 17:29:23,281 - clearml.storage - INFO - Downloaded 5.00 MB successfully from s3://aqua-ml-data/ext-qa/builds/661d9760624b51027a9e83ab/pretranslate.src.json , saved to /root/machine/ext-qa/builds/661d9760624b51027a9e83ab/pretranslate.src.json
2024-04-15 17:29:32
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/json_stream/base.py", line 269, in _find_item
    return super()._find_item(k)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/json_stream/base.py", line 227, in _find_item
    raise KeyError(k)
KeyError: 'translation'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.clearml/venvs-builds/3.11/code/untitled.py", line 13, in <module>
    run(args)
  File "/usr/local/lib/python3.11/dist-packages/machine/jobs/build_nmt_engine.py", line 79, in run
    raise e
  File "/usr/local/lib/python3.11/dist-packages/machine/jobs/build_nmt_engine.py", line 71, in run
    job.run(progress, check_canceled)
  File "/usr/local/lib/python3.11/dist-packages/machine/jobs/nmt_engine_build_job.py", line 81, in run
    inference_step_count = sum(1 for _ in src_pretranslations)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/machine/jobs/nmt_engine_build_job.py", line 81, in <genexpr>
    inference_step_count = sum(1 for _ in src_pretranslations)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/machine/jobs/shared_file_service.py", line 59, in generator
    translation=pi["translation"],
                ~~^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/json_stream/base.py", line 117, in __getitem__
    return self._find_item(k)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/json_stream/base.py", line 272, in _find_item
    raise TransientAccessException(
json_stream.base.TransientAccessException: translation not found in transient JSON stream or already passed in this stream
```

**Comment by johnml1135** [comment]
Here is what was in the json file:
![image](https://github.com/sillsdev/serval/assets/13733556/e0cdf4ea-94ff-4808-8815-880178c34aa0)

It was created incorrectly - yesterday at 05:08:52 PM EST.

Here is the log from ClearML:
```
2024-04-15 17:08:49	
serval-api <info> info: Serval.Translation.Services.EngineService[0]
      {"EngineType":"Nmt","EngineId":"66172578624b51027a9e7c3b","BuildId":"661d9760624b51027a9e83ab","HasOptions":true,"Corpora":[{"Id":"6617257e624b51027a9e7c3e","SourceLanguage":"en","TargetLanguage":"mi","TrainOnAll":true,"PretranslateAll":true,"TrainOnChapters":{"PHM":{"Chapters":[]},"2JN":{"Chapters":[]},"3JN":{"Chapters":[]}},"PretranslateChapters":{"SNG":{"Chapters":[]},"LAM":{"Chapters":[]}},"TrainOnTextIds":[],"PretranslateTextIds":[],"
2024-04-15 17:08:49	
serval-api <info> info: System.Net.Http.HttpClient.Nmt.LogicalHandler[100]
      Start processing HTTP request POST http://machine-engine/serval.translation.v1.TranslationEngineApi/StartBuild
2024-04-15 17:08:50	
serval-api <info> info: System.Net.Http.HttpClient.Nmt.ClientHandler[100]
      Sending HTTP request POST http://machine-engine/serval.translation.v1.TranslationEngineApi/StartBuild
2024-04-15 17:08:50	
serval-api <info> info: System.Net.Http.HttpClient.Nmt.ClientHandler[101]
      Received HTTP response headers after 806.5706ms - 200
2024-04-15 17:08:56	
machine-job <info> info: SIL.Machine.AspNetCore.Services.NmtPreprocessBuildJob[0]
      {"Event":"BuildPreprocess","EngineId":"66172578624b51027a9e7c3b","BuildId":"661d9760624b51027a9e83ab","NumTrainRows":53,"NumPretranslateRows":36837,"SourceLanguageResolved":"eng_Latn","TargetLanguageResolved":"mri_Latn"}
```

Nothing is showing up suspicious when it was created.  I don't know how that could have happened.  @pmachapman, it looks like the job failed half-way through through an S3 bucket error or similar.  I kicked it off again: https://app.sil.hosted.allegro.ai/projects/*/experiments/52e2aae95bbc414cbe15fdaab59e168b/info-output/log?columns=selected&columns=type&columns=name&columns=tags&columns=status&columns=project.name&columns=users&columns=started&columns=last_update&columns=last_iteration&columns=parent.name&order=-last_update&filter=&deep=true.

**Comment by pmachapman** [comment]
@johnml1135 It has failed again after your manual kickoff:

```json
{
    "id": "661e7a63624b51027a9e87b4",
    "url": "/api/v1/translation/engines/66172578624b51027a9e7c3b/builds/661e7a63624b51027a9e87b4",
    "revision": 9,
    "name": "manual_run_checking_github.com/sillsdev/serval/issues/364",
    "engine": {
      "id": "66172578624b51027a9e7c3b",
      "url": "/api/v1/translation/engines/66172578624b51027a9e7c3b"
    },
    "trainOn": [
      {
        "corpus": {
          "id": "6617257e624b51027a9e7c3e",
          "url": "/api/v1/translation/engines/66172578624b51027a9e7c3b/corpora/6617257e624b51027a9e7c3e"
        },
        "scriptureRange": "PHM;2JN;3JN"
      }
    ],
    "pretranslate": [
      {
        "corpus": {
          "id": "6617257e624b51027a9e7c3e",
          "url": "/api/v1/translation/engines/66172578624b51027a9e7c3b/corpora/6617257e624b51027a9e7c3e"
        },
        "scriptureRange": "SNG;LAM"
      }
    ],
    "step": 0,
    "percentCompleted": 0.9,
    "message": "TransientAccessException : translation not found in transient JSON stream or already passed in this stream",
    "queueDepth": 0,
    "state": "Faulted",
    "dateFinished": "2024-04-16T13:21:23.119Z",
    "options": {
      "max_steps": 20
    }
  }
```

**Comment by ddaspit** [comment]
If all we did was restart the ClearML job, then it makes sense that it would fail again. We would need to restart the job on Serval, so that it regenerates the pretranslation JSON file.

**Comment by johnml1135** [comment]
I didn't restart it using the swagger API. I'll check it out tomorrow to
see if it is the same error.

**Comment by johnml1135** [comment]
The issue appears to be that the file `pretranslate.src.json` is created incorrectly by the machine in that it uploads the first 5MB part, but then stops for some reason.  @Enkidu93 , do you know what could be going on?

**Comment by johnml1135** [comment]
I think I got it - fix coming.
