### ISSUE TITLE
Paratext Parsing crash

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#372]
This is the failure message:
```
2024-04-19 06:54:14	
machine-job <fail> fail: SIL.Machine.AspNetCore.Services.NmtPreprocessBuildJob[0]
      Build faulted (66224d553c04ab80b19bd484)
      System.NullReferenceException: Object reference not set to an instance of an object.
         at SIL.Machine.Corpora.ParatextProjectSettingsParserBase.Parse() in /app/src/SIL.Machine/Corpora/ParatextProjectSettingsParserBase.cs:line 85
         at SIL.Machine.Corpora.ParatextBackupTextCorpus..ctor(String fileName, Boolean includeMarkers) in /app/src/SIL.Machine/Corpora/ParatextBackupTextCorpus.cs:line 14
         at SIL.Machine.AspNetCore.Services.CorpusService.CreateTextCorpora(IReadOnlyList`1 files) in /app/src/SIL.Machine.AspNetCore/Services/CorpusService.cs:line 29
         at SIL.Machine.AspNetCore.Services.NmtPreprocessBuildJob.WriteDataFilesAsync(String buildId, IReadOnlyList`1 corpora, String buildOptions, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs:line 123
         at SIL.Machine.AspNetCore.Services.N
```

What could be happening?

**Comment by johnml1135** [comment]
Ah - this is already addressed with https://github.com/sillsdev/machine/pull/180.
