### ISSUE TITLE
Better error if file is missing

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#384]
If the file is not there (but it thinks it should be), it throws a 500.  It can at least throw a 500 and say why:

Internal error:
```
	
serval-api <fail> fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN35C505BF9V", Request id "0HN35C505BF9V:00000151": An unhandled exception was thrown by the application.
      System.IO.FileNotFoundException: Could not find file '/var/lib/serval/files/r4s2eajt.r50'.
      File name: '/var/lib/serval/files/r4s2eajt.r50'
         at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
         at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
         at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
         at Serval.DataFiles.Services.DataFileService.ReadAsync(String id, CancellationToken cancellationToken) in /app/src/Serval.DataFiles/Services/DataFileService.cs:line 65
         at Serval.DataFiles.Controllers.DataFilesController.DownloadAsync(String id, CancellationToken cancellationToken) in /app/src/Serval.DataFiles/Controllers/DataFilesController.cs:line 150
         at lambda_method76451(Closure, Object)
```

API error: `Error: response status is 500`

**Comment by ddaspit** [comment]
If this occurs, then something is fundamentally broken. The current error tells us exactly what we need to know.

**Comment by johnml1135** [comment]
It tells us that, but not the client of the api. We should tell them that the file is missing and they should reupload it.

**Comment by johnml1135** [comment]
@ddaspit  - are you up for displaying detailed server errors or not?  We could do it for QA at least: https://stackoverflow.com/questions/5385714/deploying-website-500-internal-server-error.
