### ISSUE TITLE
Rethink change stream usage for Mongo in DataAccess

### ISSUE THREAD

**Issue by Enkidu93** [sillsdev/serval#440]
See more information [here](https://github.com/sillsdev/serval/pull/437).

**Comment by johnml1135** [comment]
@Enkidu93, is this resolved?

**Comment by johnml1135** [comment]
Was this resolved when we did all of the locking issues?

**Comment by Enkidu93** [comment]
> Was this resolved when we did all of the locking issues?

No, it was not. Although maybe the move to EF.Core might fix it?

**Comment by pmachapman** [comment]
Resume token use is not appropriate for our scenario, as documents are deleted. My attempts to use it resulted in a lot of errors like:

```
MongoDB.Driver.MongoCommandException: Command aggregate failed: PlanExecutor error during aggregation :: caused by :: cannot resume stream; the resume token was not found. {_data: "826983EDE5000000082B042C0100296E5A100497B8B416039C47E1B5AF010738E7AB32463C6F7065726174696F6E54797065003C64656C6574650046646F63756D656E744B65790046645F696400646983EDE56A16DCE2E1C4F4B8000004"}.
    at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ProcessResponse(ConnectionId connectionId, CommandMessage responseMessage)
    at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.SendMessageAndProcessResponseAsync(CommandRequestMessage message, Int32 responseTo, IConnection connection, CancellationToken cancellationToken)
    at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ExecuteAsync(IConnection connection, CancellationToken cancellationToken)
    at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocolAsync[TResult](IWireProtocol`1 protocol, ICoreSession session, CancellationToken cancellationToken)
    at MongoDB.Driver.Core.Operations.RetryableReadOperationExecutor.ExecuteAsync[TResult](IRetryableReadOperation`1 operation, RetryableReadContext context, CancellationToken cancellationToken)
    at MongoDB.Driver.Core.Operations.ReadCommandOperation`1.ExecuteAsync(RetryableReadContext context, CancellationToken cancellationToken)
    at MongoDB.Driver.Core.Operations.AggregateOperation`1.ExecuteAsync(RetryableReadContext context, CancellationToken cancellationToken)
    at MongoDB.Driver.Core.Operations.ChangeStreamOperation`1.ExecuteAsync(IReadBinding binding, CancellationToken cancellationToken)
    at MongoDB.Driver.OperationExecutor.ExecuteReadOperationAsync[TResult](IReadBinding binding, IReadOperation`1 operation, CancellationToken cancellationToken)
    at MongoDB.Driver.MongoCollectionImpl`1.ExecuteReadOperationAsync[TResult](IClientSessionHandle session, IReadOperation`1 operation, ReadPreference readPreference, CancellationToken cancellationToken)
    at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
    at SIL.DataAccess.MongoSubscription`1.WaitForChangeAsync(Nullable`1 timeout, CancellationToken cancellationToken) in /home/peter/source/serval/src/DataAccess/src/SIL.DataAccess/MongoSubscription.cs:line 58
    at SIL.ServiceToolkit.Services.OutboxDeliveryService.ExecuteAsync(CancellationToken stoppingToken) in /home/peter/source/serval/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/OutboxDeliveryService.cs:line 39
    at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
```

Decoding the resume token referenced the last outbox_message (which was deleted):

```
{
  timestamp: new Timestamp({ t: 1770253797, i: 8 }),
  version: 2,
  tokenType: 128,
  txnOpIndex: 0,
  fromInvalidate: false,
  uuid: new UUID("97b8b416-039c-47e1-b5af-010738e7ab32"),
  eventIdentifier: {
    operationType: 'delete',
    documentKey: { _id: new ObjectId("6983ede56a16dce2e1c4f4b8") }
  }
}

```

I think we should keep our current timestamp based system, unless a specific bug can be identified and documented with it.
