### ISSUE TITLE
Could not resolve assembly error

### ISSUE THREAD

**Issue by Enkidu93** [sillsdev/serval#496]
Recently saw a new error on the machine job server:
```
fail: Hangfire.AutomaticRetryAttribute[0]
      Failed to process the job '667c0900463c96428ae5ed9b': an exception occurred.
      System.IO.FileNotFoundException: Could not resolve assembly 'SIL.Machine.AspNetCore'.
         at System.Reflection.TypeNameParser.ResolveAssembly(String assemblyName)
         at System.Reflection.TypeNameParser.GetType(String typeName, ReadOnlySpan`1 nestedTypeNames, String assemblyNameIfAny)
         at System.Reflection.TypeNameParser.Parse()
         at System.Reflection.TypeNameParser.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Assembly requestingAssembly, Boolean throwOnError, Boolean ignoreCase, Boolean extensibleParser)
         at System.Type.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError)
         at Hangfire.Common.TypeHelper.<>c.b__20_0(String name) in C:\\projects\\hangfire-525\\src\\Hangfire.Core\\Common\\TypeHelper.cs:line 83
         at System.Collections
```
@ddaspit, any clue as to what could be causing this?

**Comment by johnml1135** [comment]
hmm... https://stackoverflow.com/questions/10878602/system-io-filenotfoundexception-could-not-load-file-or-assembly-x-or-one-of-i

Did the server restart right before or after?

**Comment by johnml1135** [comment]
Let's assume this is one-off.
