### ISSUE TITLE
new USFM crash

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#589]
```
Serval.Machine.Shared.Services.PreprocessBuildJob[0]
      Build faulted (67670e60df523878b567e904)
      System.InvalidOperationException: An error occurred while parsing the text 'EXO' in project 'ABC'. Verse: EXO :0, line: 421, character: 31, error: 'Stack empty.'
       ---> System.InvalidOperationException: Stack empty.
         at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
         at SIL.Machine.Corpora.UsfmTextBase.TextRowCollector.EndVerseText(UsfmParserState state, IReadOnlyList`1 scriptureRefs)
         at SIL.Machine.Corpora.ScriptureRefUsfmParserHandlerBase.Verse(UsfmParserState state, String number, String marker, String altNumber, String pubNumber)
         at SIL.Machine.Corpora.UsfmParser.ProcessToken()
```

**Comment by Enkidu93** [comment]
Is this a test project or have you intentionally obscured the project name?

**Comment by johnml1135** [comment]
I'm checking it out now.  I'll post more data here soon (yes, I obscured the project name because I don't know if it is sensitive or not).

**Comment by johnml1135** [comment]
Minimum USFM to reproduce:
```
\id MAT - Test
\c 1
1 This is the 1\v 00 verse.
```

**Comment by johnml1135** [comment]
@Enkidu93  - I was able to identify the issue and make it reproducable (see https://github.com/sillsdev/machine/tree/usfm_error_589).  Can you bring this to completion?

**Comment by johnml1135** [comment]
@Enkidu93  - I assigned you to this - would you be able to finish this USFM bug to completion?

**Comment by Enkidu93** [comment]
> [@Enkidu93](https://github.com/Enkidu93) - I assigned you to this - would you be able to finish this USFM bug to completion?

Yes, I can do that. I've been more-or-less focused completely on word alignment (unless something urgent comes up). I was planning on tackling some of these once I'm waiting on reviews for word alignment (which should be very soon), but if any need to be prioritized, let me know & I can pause the word alignment work.

**Comment by johnml1135** [comment]
I would like to try to cut a version of Serval in the next few days.  If this could be finished up soon, that would be great.

**Comment by Enkidu93** [comment]
@johnml1135 I'm not sure quite what to do with this issue; it's a bit different than some of our other USFM bugs: What's the intended behavior? This USFM is pretty messed up 😆 . How should this be interpreted?

**Comment by johnml1135** [comment]
This may be a case to create a "nuclear" parsing option where it just passes over the verse (or paragraph) and just starts the next verse.
