### ISSUE TITLE
Machine-Engine CPU 100%

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#590]
#484 has happened again.

![Image](https://github.com/user-attachments/assets/04b6769f-ffc7-4cb5-bc45-083d75467295)
![Image](https://github.com/user-attachments/assets/db8cf9dd-a785-45aa-890d-4b0fd9685eb6)
![Image](https://github.com/user-attachments/assets/6c12cbd9-8736-42a0-a883-9af3c3c5648c)
![Image](https://github.com/user-attachments/assets/bbaa8247-c452-4ba9-a2e9-5a360d1ee7f5)

It started CPU overloading around 6:05 (UTC), but the last get word graphs were at 6:01.  There where two engines (and some files and corpora) deleted during that time as well.  The "MongoDB commands" also started in earnest right at 6:05 - which was also when the lock write operations started - 700+ per second.

Are the get word graphs a red herring?  They are all complete 3 minutes before everything opens up.  The commands that happen at 6:05 are:
* DELETE, 200, api/v{version:apiVersion}/corpora/{id}
* DELETE, 200, api/v{version:apiVersion}/files/{id}
* DELETE, 200, api/v{version:apiVersion}/translation/engines/{id}
* GET, 200
* GET, 200, api/v{version:apiVersion}/status/ping
* GET, 200, api/v{version:apiVersion}/translation/engines
* GET, 200, api/v{version:apiVersion}/translation/engines/{id}
* GET, 408, api/v{version:apiVersion}/translation/engines/{id}/current-build
* PATCH, 200, api/v{version:apiVersion}/corpora/{id}
* POST, 200, /serval.translation.v1.TranslationPlatformApi/BuildStarted
* POST, 200, /serval.translation.v1.TranslationPlatformApi/UpdateBuildStatus
* POST, 201, api/v{version:apiVersion}/corpora
* POST, 201, api/v{version:apiVersion}/files
* POST, 201, api/v{version:apiVersion}/translation/engines
* POST, 201, api/v{version:apiVersion}/translation/engines/{id}/builds
* POST, 201, api/v{version:apiVersion}/translation/engines/{id}/parallel-corpora

I wonder if it is updating the build files and then starting a build right away - there should be something on ClearML at 1:05 AM EST, but it is not there...

**Comment by johnml1135** [comment]
@Nateowami or @pmachapman  - there was a job that was started at 06:05 UTC on 12/24 but it is not showing up in my database.  Do you have a record of spinning up a build at that time?

**Comment by johnml1135** [comment]
I got the error!
```
Error occurred while committing SMT transfer engine 676a4eaadf523878b56e1866.
      System.OperationCanceledException: The operation was canceled.
         at MongoDB.Driver.Core.Misc.StreamExtensionMethods.ReadAsync(Stream stream, Byte[] buffer, Int32 offset, Int32 count, TimeSpan timeout, CancellationToken cancellationToken)
         at MongoDB.Driver.Core.Misc.StreamExtensionMethods.ReadBytesAsync(Stream stream, Byte[] buffer, Int32 offset, Int32 count, TimeSpan timeout, CancellationToken cancellationToken)
         at MongoDB.Driver.Core.Connections.BinaryConnection.ReceiveBufferAsync(CancellationToken cancellationToken)
         at MongoDB.Driver.Core.Connections.BinaryConnection.ReceiveBufferAsync(Int32 responseTo, CancellationToken cancellationToken)
         at MongoDB.Driver.Core.Connections.BinaryConnection.ReceiveBufferAsync(Int32 responseTo, CancellationToken cancellationToken)
         at MongoDB.Driver.Core.Connections.BinaryConnection.ReceiveMessageAsync(Int32 responseTo, IMessageEncoderSelector encoderSelector, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
         at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.PooledConnection.ReceiveMessageAsync(Int32 responseTo, IMessageEncoderSelector encoderSelector, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
         at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.SendMessageAndProcessResponseAsync(CommandRequestMessage message, Int32 responseTo, IConnection connection, CancellationToken cancellationToken)
         at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ExecuteAsync(IConnection connection, CancellationToken cancellationToken)
         at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocolAsync[TResult](IWireProtocol`1 protocol, ICoreSession session, CancellationToken cancellationToken)
         at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocolAsync(IChannelSource channelSource, ICoreSessionHandle session, ReadPreference readPreference, CancellationToken cancellationToken)
         at MongoDB.Driver.Core.Operations.WriteCommandOperation`1.ExecuteAsync(IWriteBinding binding, CancellationToken cancellationToken)
         at MongoDB.Driver.Core.Operations.FindAndModifyOperationBase`1.ExecuteAttemptAsync(RetryableWriteContext context, Int32 attempt, Nullable`1 transactionNumber, CancellationToken cancellationToken)
         at MongoDB.Driver.Core.Operations.RetryableWriteOperationExecutor.ExecuteAsync[TResult](IRetryableWriteOperation`1 operation, RetryableWriteContext context, CancellationToken cancellationToken)
         at MongoDB.Driver.Core.Operations.RetryableWriteOperationExecutor.ExecuteAsync[TResult](IRetryableWriteOperation`1 operation, IWriteBinding binding, Boolean retryRequested, CancellationToken cancellationToken)
         at MongoDB.Driver.OperationExecutor.ExecuteWriteOperationAsync[TResult](IWriteBinding binding, IWriteOperation`1 operation, CancellationToken cancellationToken)
         at MongoDB.Driver.MongoCollectionImpl`1.ExecuteWriteOperationAsync[TResult](IClientSessionHandle session, IWriteOperation`1 operation, CancellationToken cancellationToken)
         at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
         at SIL.DataAccess.MongoRepository`1.UpdateAsync(Expression`1 filter, Action`1 update, Boolean upsert, Boolean returnOriginal, CancellationToken cancellationToken)
         at Serval.Machine.Shared.Services.DistributedReaderWriterLock.TryAcquireWriterLock(String lockId, TimeSpan lifetime, CancellationToken cancellationToken) in /app/src/Machine/src/Serval.Machine.Shared/Services/DistributedReaderWriterLock.cs:line 217
         at Serval.Machine.Shared.Services.DistributedReaderWriterLock.WriterLockAsync[T](Func`2 action, Nullable`1 lifetime, CancellationToken cancellationToken) in /app/src/Machine/src/Serval.Machine.Shared/Services/DistributedReaderWriterLock.cs:line 157
         at Serval.Machine.Shared.Services.DistributedReaderWriterLock.WriterLockAsync[T](Func`2 action, Nullable`1 lifetime, CancellationToken cancellationToken) in /app/src/Machine/src/Serval.Machine.Shared/Services/DistributedReaderWriterLock.cs:line 167
         at Serval.Machine.Shared.Services.SmtTransferEngineStateService.CommitAsync(IDistributedReaderWriterLockFactory lockFactory, IRepository`1 engines, TimeSpan inactiveTimeout, CancellationToken cancellationToken) in /app/src/Machine/src/Serval.Machine.Shared/Services/SmtTransferEngineStateService.cs:line 44
```

It occurred when I restarted the engine-server.  But I also got the same error for the following engines:
* 676a4eaadf523878b56e1866
* 6763100edf523878b563ec7d
* 6769423bdf523878b56af67e
* 67696761df523878b56c5020
* 67618c98df523878b561813e
* 6760380bdf523878b55d10bb

There were 6 SMT engines that were not being committed!?!?! What happened!?!?

**Comment by johnml1135** [comment]
@Nateowami and @pmachapman  - it's looking like you are getting quite a few 409's in response to a "GetWordGraph" If you do, it means that the engine "is not built yet" and you can kick off a build.

**Comment by johnml1135** [comment]
I figured it out - all of the engines in question have been deleted.  It appears that the deletion happened but there were other updates also happening at the same time.  This may have been due to the "rolling updates" that SF appears to have been making.  Still, although the behavior can be undefined if the engine was just deleted, it should at least not lock up the machine.  How can we graciously cancel these operations if the engine has been deleted?  It appears we are trying to "cancel" the operation and commit it at the same time (but it may already be deleted, etc.)
