### ISSUE TITLE
Grpc call canceled by client - not a failure

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#81]
Here are 3 occurances of I think the same thing...

```
[From Serval]
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMSKT8T418KU", Request id "0HMSKT8T418KU:00000002": An unhandled exception was thrown by the application.
      Grpc.Core.RpcException: Status(StatusCode="Cancelled", Detail="Call canceled by the client.", DebugException="System.OperationCanceledException: The operation was canceled.")
       ---> System.OperationCanceledException: The operation was canceled.
         --- End of inner exception stack trace ---
         at Serval.Translation.Services.EngineService.GetWordGraphAsync(String engineId, String segment, CancellationToken cancellationToken) in /app/src/Serval.Translation/Services/EngineService.cs:line 100
         at Serval.Translation.Controllers.TranslationEnginesController.GetWordGraphAsync(String id, String segment, CancellationToken cancellationToken) in /app/src/Serval.Translation/Controllers/TranslationEnginesController.cs:line 309
         at lambda_method367(Closure , Object )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

[From Machine]
[41m[30mfail[39m[22m[49m: Grpc.AspNetCore.Server.ServerCallHandler[6]
      Error when executing service method 'GetWordGraph'.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at SIL.Machine.Utils.ObjectPool`1.GetAsync(CancellationToken cancellationToken) in /app/src/SIL.Machine/Utils/ObjectPool.cs:line 56
         at SIL.Machine.Translation.Thot.ThotSmtModel.GetWordGraphAsync(String segment, CancellationToken cancellationToken) in /app/src/SIL.Machine.Translation.Thot/ThotSmtModel.cs:line 120
         at SIL.Machine.Translation.HybridTranslationEngine.GetWordGraphAsync(String segment, CancellationToken cancellationToken) in /app/src/SIL.Machine/Translation/HybridTranslationEngine.cs:line 208
         at SIL.Machine.AspNetCore.Services.SmtTransferEngineService.GetWordGraphAsync(String engineId, String segment, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs:line 97
         at SIL.Machine.AspNetCore.Services.SmtTransferEngineService.GetWordGraphAsync(String engineId, String segment, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs:line 97
         at SIL.Machine.AspNetCore.Services.ServalTranslationEngineServiceV1.GetWordGraph(GetWordGraphRequest request, ServerCallContext context) in /app/src/SIL.Machine.AspNetCore/Services/ServalTranslationEngineServiceV1.cs:line 61
         at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest resolvedRequest, ServerCallContext resolvedContext)
         at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest resolvedRequest, ServerCallContext resolvedContext)
         at SIL.Machine.AspNetCore.Services.UnimplementedInterceptor.UnaryServerHandler[TRequest,TResponse](TRequest request, ServerCallContext context, UnaryServerMethod`2 continuation) in /app/src/SIL.Machine.AspNetCore/Services/UnimplementedInterceptor.cs:line 21
         at Grpc.Shared.Server.InterceptorPipelineBuilder`2.<>c__DisplayClass5_0.<<UnaryPipeline>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Grpc.Shared.Server.InterceptorPipelineBuilder`2.<>c__DisplayClass5_0.<<UnaryPipeline>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)

[From Serval]
\u001b[41m\u001b[30mfail\u001b[39m\u001b[22m\u001b[49m: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id \"0HMSKT8T418G2\", Request id \"0HMSKT8T418G2:00000002\": An unhandled exception was thrown by the application.
      Grpc.Core.RpcException: Status(StatusCode=\"Cancelled\", Detail=\"Call canceled by the client.\", DebugException=\"System.OperationCanceledException: The operation was canceled.\")
       ---> System.OperationCanceledException: The operation was canceled.
         --- End of inner exception stack trace ---
         at Serval.Translation.Services.EngineService.GetWordGraphAsync(String engineId, String segment, CancellationToken cancellationToken) in /app/src/Serval.Translation/Services/EngineService.cs:line 100
         at Serval.Translation.Controllers.TranslationEnginesController.GetWordGraphAsync(String id, String segment, CancellationToken cancellationToken) in /app/src/Serval.Translation/Controllers/TranslationEnginesController.cs:line 309
         at lambda_method367(Closure , Object )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

What exactly happened?  Wordgraph?  Client cancelled?  This should (likely) be an info, not a failure.

**Comment by johnml1135** [comment]
A few more messages before:
![image](https://github.com/sillsdev/serval/assets/13733556/3262bb5d-ac40-4cc8-81f1-aed3eabe0191)
One idea is that two requests were sent at nearly exactly the same time - and that Serval cracked under it.
Or that the cancellation token was invoked - how would we figure that out?

**Comment by ddaspit** [comment]
Maybe the SF client in the browser cancelled the request to the SF backend and it bubbled all the way up to the engine.

**Comment by Enkidu93** [comment]
I'm not sure how to address this. Is this reproducible? Is it happening often in the logs, @johnml1135? I could certainly filter the logs such that these exceptions are logged as info rather than error (preferable for alerting purposes etc.) if indeed they are a product of normal use as it seems they are.

**Comment by ddaspit** [comment]
We could try calling the Serval endpoint using Postman or something like it and cancelling the request to see if it causes this.

**Comment by johnml1135** [comment]
It is a bug (one way or the other).  I am inclined to just leave it alone for now and see if it happens again.

**Comment by Enkidu93** [comment]
The same bug came up for me when running tests as I cancelled a request. Seems like it's likely normal behavior; should we set up a filter then to keep this from registering as a fail?

**Comment by johnml1135** [comment]
Yes - it should not register as a fail if it is cancelled from the client.  A filter should be fine.

**Comment by Enkidu93** [comment]
Fixed [here](https://github.com/sillsdev/serval/pull/146).
